#StopSleep v 1.2.5
#hi
#Message when someone without the permission stopsleep.silent attempts to sleep:
Message: "&cAin't no rest for the wicked"
#Whether the bed should break on attempting to sleep/use the bed
Break Bed: false
#Whether beds should cause an explosion effect (Sounds, player/entity damage)
Explosions: false
#If the above is true, whether explosions should cause fire, or block damage
Explosion Fire: false
Explosion Block Damage: false
