name: Stopsleep
version: '${project.version}'
main: me.adhdmc.stopsleep.Stopsleep
api-version: 1.17
authors: [ IllogicalSong ]
permissions:
  stopsleep.bypass:
    [bypass stopsleep]
  stopsleep.silent:
    [disable messages from stopsleep]
description: It stops you from sleeping. Yep, that's it.