name: Stopsleep
version: ${project.version}
main: me.adhdmc.stopsleep.Stopsleep
api-version: 1.13
authors: [ IllogicalSong ]
permissions:
  stopsleep.bypass:
    description: bypass stopsleep
  stopsleep.silent:
    description: disable messages from stopsleep
  stopsleep.reload:
    description: reload plugin config
description: "It stops you from sleeping. Yep, that's it."
commands:
  stopsleep:
    description: Reloads the config for stopsleep
    usage: /stopsleep reload
    permission: stopsleep.reload
softdepend: [CoreProtect]
